name: ams_frontend
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  json_annotation: ^4.8.0
  logger: ^1.2.2
  lottie: ^2.2.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
