name: ams_frontend
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  convex_bottom_bar: ^3.2.0
  cron: ^0.5.1
  device_preview: ^1.1.0
  dio: ^5.0.1
  easy_cron: ^0.9.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  flutter_speed_dial: ^6.2.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^8.5.0
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  logger: ^1.2.2
  lottie: ^2.2.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.0.2
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^21.1.38
  table_calendar: ^3.0.1
  
dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  source_gen: ^1.1.0
  riverpod_generator: ^2.1.4
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
  fonts:
    - family: HP Simplified Hans
      fonts:
        - asset: assets/fonts/HP Simplified Hans Regular.ttf