on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      - run: flutter pub get
      - run: flutter pub run build_runner build -d
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
      - run: flutter build linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux/x64/release/bundle
